<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ckff3b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ckff3b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5ckff3b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5ckff3b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5ckff3b\appDevDebugProjectContainer([
    'container.build_hash' => '5ckff3b',
    'container.build_id' => '0c2f54b9',
    'container.build_time' => 1564813037,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ckff3b');
