<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ9fa0x3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ9fa0x3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ9fa0x3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ9fa0x3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJ9fa0x3\appDevDebugProjectContainer([
    'container.build_hash' => 'J9fa0x3',
    'container.build_id' => 'ce88cd71',
    'container.build_time' => 1564733981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ9fa0x3');
