<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerU0jyent\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU0jyent/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU0jyent.legacy');
=======
if (\class_exists(\Container5ckff3b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ckff3b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5ckff3b.legacy');
>>>>>>> parent of fcd1fc5... upload

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerU0jyent\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerU0jyent\appDevDebugProjectContainer([
    'container.build_hash' => 'U0jyent',
    'container.build_id' => '9d7938f9',
    'container.build_time' => 1566123057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU0jyent');
=======
    \class_alias(\Container5ckff3b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5ckff3b\appDevDebugProjectContainer([
    'container.build_hash' => '5ckff3b',
    'container.build_id' => 'a1fd8f2f',
    'container.build_time' => 1564833036,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ckff3b');
>>>>>>> parent of fcd1fc5... upload
